### ISSUE TITLE
Add a new section in the Docs for other JSON Schema resources

### ISSUE THREAD

**Issue by benjagm** [json-schema-org/website#282]
#### Description
If would be great to have resources section to show articles, papers, books podcasts and any other type of resources. We'll use json to store the data and provide dynamic UX.

Content types: 
* Articles
* Books
* Courses
* Videos
* Podcasts
* Papers

Data structure example:
````
- title: Using JSON Schema
  url: https://books.apple.com/us/book/using-json-schema/id903248630
  year: 2014
  type: books
  summary: Learn and Apply JSON Schema by Example, with JavaScript (Node.js) and Python Programs
- title: JSON at Work
  url: https://www.oreilly.com/library/view/json-at-work/9781491982389/
  year: 2017
  type: books
  summary: A comprehensive overview of the JSON ecosystem, including JSON Schema
````
An amazing source of information will be: https://github.com/sourcemeta/awesome-jsonschema/blob/master/data.yaml

A possible prototype for this may be:

Resources menu:
<img width="356" alt="Screenshot 2024-02-10 at 18 51 04" src="https://github.com/json-schema-org/website/assets/40007659/db480fbd-5e27-4506-b989-2e64b256fb13">

Resource category page (example):
![Untitled presentation (1)](https://github.com/json-schema-org/website/assets/40007659/d562292c-5a63-4e4e-a8cd-3983cfcfe49a)

**Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

**Comment by benjagm** [comment]
I have some progress in this draft PR #281 but I'd love to have someone to continue the development.

**Comment by Min2who** [comment]
> I have some progress in this draft PR #281 but I'd love to have someone to continue the development.

@benjagm can i help you with it?

**Comment by benjagm** [comment]
> can i help you with it?

@Min2who of course! Thanks a lot!! Please go ahead. (check my draft PR with the side menu logic)

**Comment by Akshaybagai52** [comment]
Hey @benjagm 
Can I work on this issue
Thanks

**Comment by benjagm** [comment]
> @benjagm can I look into this?

Available to work on this one?

**Comment by Atharva-Kanherkar** [comment]
Hi, if no one is working on this, i would like to work on this. 
Seems like a good issue to get hands on with the codebase!
> @Akshaybagai52 Available to work on this one?

**Comment by benjagm** [comment]
Please go ahead @Akshaybagai52 ! Thanks for your support!

**Comment by Akshaybagai52** [comment]
Thanks @benjagm for assigning this issue would share the progress

**Comment by Akshaybagai52** [comment]
Hey @benjagm 
is this looking good ?
![image](https://github.com/json-schema-org/website/assets/100753870/5c494fb9-8021-449f-80b9-2167248ce0ef)
and can you suggest me good icon if there is any already present in the repo because I've find some but they are big in size
and right now the routes I made is like that 
![image](https://github.com/json-schema-org/website/assets/100753870/2335d87e-8b8b-4880-9e26-50e406a0aa60)
is these correct or you want me to change the route name 
Thanks

**Comment by benjagm** [comment]
> is this looking good ?

Looks good but we'd like the categories to be loaded dynamically from the YAML in the nodes "name"

**Comment by Akshaybagai52** [comment]
Okay I will check that

> > is this looking good ?
> 
> Looks good but we'd like the categories to be loaded dynamically from the YAML in the nodes "name"

**Comment by benjagm** [comment]
The YAML does not exists. You'll need to create or import it from : https://github.com/sourcemeta/awesome-jsonschema

And put it into the data folder.

**Comment by Akshaybagai52** [comment]
> The YAML does not exists. You'll need to create or import it from : https://github.com/sourcemeta/awesome-jsonschema
> 
> And put it into the data folder.

Is there any code related to YAML which is already present in the "website" repo because I've checked the code for docs section it is using same thing as I shown above

**Comment by benjagm** [comment]
> section it is using same thing as I shown above

Your approach to create new static links in the side bar is correct, however for this feature we need to dynamically create those links depending on the database with resources available in a new yaml file we are going to create inside the folder "data". This file will have this structure:

````
- name: Books
  resources:
    - name: Unifying Business, Data, and Code - Designing Data Products with JSON Schema
      url: https://www.oreilly.com/library/view/unifying-business-data/9781098144999/
      Description: Covers topics such as writing your own JSON Schema vocabularies, understanding JSON Schema annotations, and hosting your own JSON Schema registries. More importantly, our book teaches you a methodology for effective data management.
      year: 2024
- name: Articles
  resources:
    - name: [How KrakenD API Gateway uses JSON Schema](https://www.krakend.io/blog/json-schema-use-case/)
      url: https://www.krakend.io/blog/json-schema-use-case/
      Description: A summary of how KrakenD uses JSON Schema in production
      year: 2023
````

And we'll import data from here:
https://github.com/sourcemeta/awesome-jsonschema

Before start coding, make sure you understand the requirements described in the body of the issue. The whole point of this feature is dynamically get data from that yaml and build the menu and the resource page with search engine.

If this is not clear in the description of the issue, happy to provide more clarifications.
